Added Support for Returning Attention Scores in TransformerEncoder call
keras-team/keras-hub pull request #1879
Opened 2024-09-25 20:37 UTC by anirudhr20

**Summary:** This pull request introduces a new feature that adds support for optionally returning attention scores in the `TransformerEncoder` class. This is controlled by the `return_attention_scores` flag, which when set to `True`, returns both the output and the attention scores from the attention mechanism.

**Changes Introduced:**
- Updated the call method in the `TransformerEncoder` to handle the `return_attention_scores` flag.
- Refactored the code to ensure that the attention scores are computed and returned when required.
- Updated the documentation in the `call` method to reflect the changes.
- Added unit tests to ensure the correctness of this feature using pytest.

**Testing:**
Ran the unit tests to verify that the `return_attention_scores` flag works as expected.
`return_attention_scores=True` (verifies that attention scores are returned and the shapes are correct).
Related Issue: https://github.com/keras-team/keras-hub/issues/1644

2024-10-18 19:06 UTC, SamanehSaadat requested changes
Thanks, @anirudhr20! The PR looks great! I just left a couple of nit comments in the test.

2024-10-21 17:30 UTC, anirudhr20 commented on keras_hub/src/layers/modeling/transformer_encoder_test.py
> +        print(attention_scores)
Yes will remove the print statement. Thanks for pointing it out!

2024-10-21 18:16 UTC, anirudhr20 commented on keras_hub/src/layers/modeling/transformer_encoder_test.py
> +        assert attention_scores.shape == [1, 2, 4, 4]
Thanks I have made the changes

2024-10-21 19:01 UTC, SamanehSaadat commented on keras_hub/src/layers/modeling/transformer_encoder_test.py
> +        assert attention_scores.shape == [1, 2, 4, 4]
Thanks for making the changes!

2024-10-21 19:01 UTC, SamanehSaadat approved these changes
Thanks for the PR!

2024-10-21 19:01 UTC, merged