Add download support for modelscople.
keras-team/keras-hub pull request #2032
Opened 2024-12-25 04:45 UTC by pass-lin

Due to relevant legal restrictions of the Chinese government, Chinese users find it quite inconvenient to use HF. 
Therefore, Chinese users often use the Chinese version of HF, which is [ModelScope](https://www.modelscope.cn/models/LLM-Research/Llama-3.3-70B-Instruct/files). 
Considering this aspect, I think we should add download support for ModelScope.
Generally, Chinese users use it as a cloud disk for storing hf data. Therefore, we only need to make slight changes in the download section, and the other parts are exactly the same as hf.
The usage is similar to hf.
```
modelscope://username/bert_base_en
```

2025-01-09 23:18 UTC, mattdangerw commented
Thanks for the PR! We are checking this out, and also considering whether we should just build a general method to allow downloads from different sources (e.g. register a new provider).

2025-01-10 08:15 UTC, pass-lin commented
> 感谢 PR！我们正在检查这一点，并考虑是否应该构建一个通用方法来允许从不同来源下载（例如，注册一个新的提供商）。



> Thanks for the PR! We are checking this out, and also considering whether we should just build a general method to allow downloads from different sources (e.g. register a new provider).

Thank you. The main reason is that we are limited by the risk of the Chinese government's control over download sources from other regions. For example, hf was initially allowed to be used in China, but later we couldn't connect to it directly, and we could only use the unstable mirror sites.
There is also a situation where Kaggle seems to have no servers in China, so the download is unstable.
Therefore, we hope to have a Chinese version available for selection, to make it more convenient for Chinese Keras users to use. We hope you can understand this.
But if your general download source still needs to connect to servers outside of China, there are still relevant risks involved.

2025-01-13 22:27 UTC, mattdangerw commented
@pass-lin yes definitely! For sure we want there to be a way to use models with modelscope. And advantage of a "plugin" style api would be that people could also use this for third own private hosting (e.g. s3 bucket, or some custom remote file storage, etc).

Sorry the process on this one might be slightly longer since it's adding a new (soft) dependency, but we are checking this out!

2025-01-29 21:01 UTC, divyashreepathihalli commented on keras_hub/src/utils/preset_utils.py
> +                "`from_preset()` requires the `modelscope` package to "
the error message can modified as follows
    "To load a preset from ModelScope {preset} using `from_preset`, install the "
    "`modelscope` package with: `pip install modelscope`."

2025-01-29 21:02 UTC, divyashreepathihalli commented on keras_hub/src/utils/preset_utils.py
> +                "Unexpected ModelScope preset. Hugging Face model handles "
NIT: Typo - Hugging Face model handles -> ModelScope

2025-01-29 21:05 UTC, divyashreepathihalli requested changes
Thank you for the PR @pass-lin. Left some comments. As soon as they are addressed, this is ready to merge

2025-01-29 21:05 UTC, divyashreepathihalli commented on keras_hub/src/utils/preset_utils.py
> +                "should have the form 'modelscope://{org}/{model}'. For example, "
Nit: improve error message as - ModelScope handles should follow the format "
    f"'modelscope://{{org}}/{{model}}' (e.g., 'modelscope://username/bert_base_en'). "
    f"Received: preset='{preset}'.

2025-02-05 15:08 UTC, pass-lin commented
> Thank you for the PR @pass-lin. Left some comments. As soon as they are addressed, this is ready to merge

OK, I have modified the error message.

2025-02-06 23:18 UTC, divyashreepathihalli approved these changes

2025-02-07 03:09 UTC, pass-lin commented
@divyashreepathihalli 
Do I need to rerun the format script?

2025-02-07 03:14 UTC, divyashreepathihalli commented
@pass-lin yes, you would need to install ruff `pip install ruff` and run `shell/format.sh` at root. Also rebase your branch with master. Thanks!

2025-02-10 09:27 UTC, merged